// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/terms-of-service": {
    params: {};
  };
  "/shop/:productId": {
    params: {
      "productId": string;
    };
  };
  "/api/revalidate": {
    params: {};
  };
  "/artists": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/artists/:slug": {
    params: {
      "slug": string;
    };
  };
  "/shop": {
    params: {};
  };
  "/lookbook": {
    params: {};
  };
  "/story": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products/:handle" | "/terms-of-service" | "/shop/:productId" | "/api/revalidate" | "/artists" | "/privacy-policy" | "/artists/:slug" | "/shop" | "/lookbook" | "/story" | "/faq" | "/*";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/terms-of-service.tsx": {
    id: "routes/terms-of-service";
    page: "/terms-of-service";
  };
  "routes/shop.$productId.tsx": {
    id: "routes/shop.$productId";
    page: "/shop/:productId";
  };
  "routes/api.revalidate.tsx": {
    id: "routes/api.revalidate";
    page: "/api/revalidate";
  };
  "routes/artists._index.tsx": {
    id: "routes/artists._index";
    page: "/artists";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/artists.$slug.tsx": {
    id: "routes/artists.$slug";
    page: "/artists/:slug";
  };
  "routes/shop._index.tsx": {
    id: "routes/shop._index";
    page: "/shop";
  };
  "routes/lookbook.tsx": {
    id: "routes/lookbook";
    page: "/lookbook";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/story.tsx": {
    id: "routes/story";
    page: "/story";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};