// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/terms-of-service": {
    params: {};
  };
  "/shop/:productId": {
    params: {
      "productId": string;
    };
  };
  "/api/revalidate": {
    params: {};
  };
  "/artists": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/artists/:slug": {
    params: {
      "slug": string;
    };
  };
  "/shop": {
    params: {};
  };
  "/lookbook": {
    params: {};
  };
  "/story": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products/:handle" | "/terms-of-service" | "/shop/:productId" | "/api/revalidate" | "/artists" | "/privacy-policy" | "/artists/:slug" | "/shop" | "/lookbook" | "/story" | "/faq" | "/*" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/terms-of-service.tsx": {
    id: "routes/terms-of-service";
    page: "/terms-of-service";
  };
  "routes/shop.$productId.tsx": {
    id: "routes/shop.$productId";
    page: "/shop/:productId";
  };
  "routes/api.revalidate.tsx": {
    id: "routes/api.revalidate";
    page: "/api/revalidate";
  };
  "routes/artists._index.tsx": {
    id: "routes/artists._index";
    page: "/artists";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/artists.$slug.tsx": {
    id: "routes/artists.$slug";
    page: "/artists/:slug";
  };
  "routes/shop._index.tsx": {
    id: "routes/shop._index";
    page: "/shop";
  };
  "routes/lookbook.tsx": {
    id: "routes/lookbook";
    page: "/lookbook";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/story.tsx": {
    id: "routes/story";
    page: "/story";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/omergeva/code/omergeva/dub-denim/semiaquatics-hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/terms-of-service": typeof import("./app/routes/terms-of-service.tsx");
  "routes/shop.$productId": typeof import("./app/routes/shop.$productId.tsx");
  "routes/api.revalidate": typeof import("./app/routes/api.revalidate.tsx");
  "routes/artists._index": typeof import("./app/routes/artists._index.tsx");
  "routes/privacy-policy": typeof import("./app/routes/privacy-policy.tsx");
  "routes/artists.$slug": typeof import("./app/routes/artists.$slug.tsx");
  "routes/shop._index": typeof import("./app/routes/shop._index.tsx");
  "routes/lookbook": typeof import("./app/routes/lookbook.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/story": typeof import("./app/routes/story.tsx");
  "routes/faq": typeof import("./app/routes/faq.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
  "/Users/omergeva/code/omergeva/dub-denim/semiaquatics-hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};